[mypy]
python_version = 3.12
strict = false
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[mypy-tweepy.*]
ignore_missing_imports = true

[mypy-praw.*]
ignore_missing_imports = true

[mypy-prawcore.*]
ignore_missing_imports = true

[mypy-spacy.*]
ignore_missing_imports = true

[mypy-en_core_web_sm.*]
ignore_missing_imports = true
