"""Technology name validation — whitelist approach."""

from __future__ import annotations

# Known technology names — only these pass through from title extraction
KNOWN_TECH: set[str] = {
    # Languages
    "python",
    "javascript",
    "typescript",
    "rust",
    "go",
    "golang",
    "java",
    "kotlin",
    "swift",
    "ruby",
    "elixir",
    "zig",
    "haskell",
    "ocaml",
    "gleam",
    "mojo",
    "lua",
    "perl",
    "php",
    "scala",
    "clojure",
    "erlang",
    "dart",
    "julia",
    "fortran",
    "c",
    "c++",
    "c#",
    "csharp",
    "r",
    "sql",
    "html",
    "css",
    "wasm",
    "assembly",
    # Frameworks & Libraries
    "react",
    "vue",
    "angular",
    "svelte",
    "nextjs",
    "nuxt",
    "remix",
    "astro",
    "django",
    "flask",
    "fastapi",
    "express",
    "nestjs",
    "spring",
    "rails",
    "laravel",
    "phoenix",
    "gin",
    "fiber",
    "actix",
    "axum",
    "rocket",
    "tailwind",
    "bootstrap",
    "htmx",
    "alpine",
    "solid",
    "qwik",
    "hono",
    "pytorch",
    "tensorflow",
    "keras",
    "scikit-learn",
    "pandas",
    "numpy",
    "langchain",
    "llamaindex",
    "huggingface",
    "transformers",
    # Tools & Platforms
    "docker",
    "kubernetes",
    "k8s",
    "terraform",
    "ansible",
    "jenkins",
    "nginx",
    "caddy",
    "git",
    "github",
    "gitlab",
    "vscode",
    "neovim",
    "vim",
    "emacs",
    "linux",
    "ubuntu",
    "debian",
    "fedora",
    "nixos",
    "nix",
    "macos",
    "windows",
    "aws",
    "gcp",
    "azure",
    "vercel",
    "netlify",
    "cloudflare",
    "railway",
    "fly",
    "node",
    "nodejs",
    "deno",
    "bun",
    "npm",
    "yarn",
    "pnpm",
    "vite",
    "webpack",
    "esbuild",
    "rollup",
    "turbopack",
    # Databases
    "postgres",
    "postgresql",
    "mysql",
    "sqlite",
    "redis",
    "mongodb",
    "cassandra",
    "supabase",
    "neon",
    "turso",
    "planetscale",
    "duckdb",
    "clickhouse",
    "drizzle",
    "prisma",
    "typeorm",
    "sqlalchemy",
    # AI/ML
    "openai",
    "gpt",
    "gpt4",
    "gpt5",
    "claude",
    "gemini",
    "llama",
    "mistral",
    "ollama",
    "copilot",
    "cursor",
    "chatgpt",
    "midjourney",
    "stable-diffusion",
    "deepseek",
    "anthropic",
    "perplexity",
    "groq",
    # DevOps & Infra
    "grafana",
    "prometheus",
    "datadog",
    "sentry",
    "elasticsearch",
    "kafka",
    "rabbitmq",
    "celery",
    "airflow",
    "pulumi",
    "vagrant",
    # Other notable tech
    "graphql",
    "grpc",
    "rest",
    "websocket",
    "oauth",
    "jwt",
    "webassembly",
    "electron",
    "tauri",
    "flutter",
    "react-native",
    "unity",
    "unreal",
    "godot",
    "blender",
    "figma",
    "notion",
    "obsidian",
    "raycast",
    "bitcoin",
    "ethereum",
    "solana",
    "blockchain",
}


def is_valid_tech_name(name: str) -> bool:
    """Check if a name is a recognized technology."""
    from src.categorization.resolver import get_resolver

    cleaned = name.lower().strip()
    if len(cleaned) < 2:
        return False
    return get_resolver().resolve(cleaned) is not None


def is_valid_language(name: str) -> bool:
    """Check if a GitHub language name is valid."""
    cleaned = name.lower().strip()
    if len(cleaned) < 2:
        return False
    if cleaned.isdigit():
        return False
    return True
